name: preparations for updates
description: prepare environment for jobs from `auto-updates` workflow
inputs:
    toolchain:
        description: 'Rust toolchain'
        default: 'nightly'
runs:
    using: composite
    steps:
        - name: Set up Rust
          run: |
              rustup set profile minimal
              rustup toolchain install ${{ inputs.toolchain }} --component rust-src rustfmt clippy  # should be synchronized with `check` workflow
              rustup default ${{ inputs.toolchain }}

        - name: Set up git user
          run: |
              git config --local user.email "intellij.rust@gmail.com"
              git config --local user.name "intellij-rust-bot"
          shell: bash
