branches:
  except:
    - staging.tmp

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - appveyor DownloadFile https://win.rustup.rs -FileName rustup-init.exe
  - rustup-init.exe -y
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - rustfmt --help || cargo install rustfmt --force

build_script:
  - gradlew.bat assemble testClasses --no-daemon

test_script:
  - gradlew.bat check --no-daemon

cache:
  - C:\Users\appveyor\.cargo\registry
  - C:\Users\appveyor\.cargo\bin
  - C:\Users\appveyor\.gradle
