name: regressions

on: [ workflow_dispatch, pull_request ]

# Allow cancelling all previous runs for the same branch
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    main:
        uses: ./.github/workflows/regressions-template.yml
        with:
            projects-matrix-file: .github/workflows/regressions.json
            analyze-dependencies: false
